### PR TITLE
[WIP] Glowing party members #14

### LINKED ISSUE #14: [Feature Request] Party Members Glowing Effect
**Is your feature request related to a problem? Please describe.**
On many servers and especially RPG servers the amount of particles used can sometimes mess with the vision of the player.

**Describe the solution you'd like**
A glowing effect on each party member of the same party would be ideal especially when there are targeted ally abilities that can be used.

**Additional context**
If there could be an option to also customise the colour of the glow effect that would add more flexibility.

### PR DESCRIPTION
**Pull request by neYaANK**
Resolves #14
Added ProtocolLib as I don't think it's achievable without editing packets. Currently it makes party members glow in white. 
Should the color of glow be set using command or config? Also should the current player see himself as glowing?

### CODE REVIEW

**Comment by Travja** [comment]
This can be done with team on a scoreboard. You just would only want to give the scoreboard to the party members so others don't see them glowing when they shouldn't be. This excerpt is from ProRPGItems item-hints module that makes items glow. https://github.com/promcteam/prorpgitems/blob/dev/src/main/java/su/nightexpress/quantumrpg/modules/list/itemhints/ItemHintsManager.java#L171-L196

**Comment by neYaANK** [comment]
Oh, so there is a simplier way. I'll check it out and see what I can do

**Comment by neYaANK** [comment]
After experimenting with scoreboards I managed to change glow color for party members via `Team`, but I can't find a way for player's to be glowing only for `Team`'s members. From what I saw, `Team` is only capable of changing the glow colour, where the glowing state of player being set with `player.setGlow()`. So, by not giving scoreboard to non-party members all I can achieve is seeing white glow (without a colour) for non-party members and with color for party members. Didn't work with `Scoreboard` and `Team` so maybe I misunderstood something though

**Comment by Travja** [comment]
If I'm not mistaken, you can set the players to be glowing without having to use `setGlowing` as the method itself will show the player glowing for everyone. I'd have to do some messing around and see if I can get you a minimum example of this, but I'm a little short on time at the moment.

**Comment by Travja** [comment]
Closing PR as this implementation really isn't the preferred implementation, and the PR is stale.

**Pull request closed without merging**
